# Generated by Django 6.0.5 on 2026-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txn',
            name='status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Khalti Process', 'Khalti Process'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('User canceled', 'User Canceled')], default='Initial', max_length=20),
        ),
    ]
