# Generated by Django 6.0.5 on 2026-06-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0002_alter_txn_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txn',
            old_name='loaction',
            new_name='location',
        ),
    ]
